# Generated by Django 5.0.6 on 2024-05-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fechaDeEntrega', models.DateField()),
                ('Entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('profesion', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='camada',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
